import { CategoryId, CategoryInfo, DanceItem } from '../types';

/* 
  =============================================================================
  HOW TO ADD CONTENT & IMAGES
  =============================================================================
  
  1. PREPARING IMAGES:
     - Go to your project folder.
     - Open the 'public' folder.
     - Create a folder named 'images' (if it doesn't exist).
     - Create subfolders for categories: 
       'samutha', 'asamutha', 'navarasas', 'head', 'neck', 'eye', 'eyebrow'.
     - Save your PNG files there matching the IDs below.
  
  2. ADDING A NEW DANCE ITEM:
     - Scroll down to 'SAMPLE_ITEMS' array.
     - Copy one of the objects (curly braces { ... }).
     - Paste it and change the values.
  
  3. CHANGING HERO IMAGES (Top of page banners):
     - Update the 'heroImage' URL in the CATEGORIES object below.
*/

// Common Banner Image
const COMMON_BANNER = '/images/general/banner.png';

// Category Metadata
export const CATEGORIES: Record<CategoryId, CategoryInfo> = {
  [CategoryId.SAMUTHA]: {
    id: CategoryId.SAMUTHA,
    title: 'Samutha Hasta',
    subtitle: 'Single Hand Gestures',
    description: 'The 28 Single Hand Gestures (Asamyuta Hastas) according to the Abhinaya Darpana. These form the alphabet of Indian Classical Dance.',
    heroImage: COMMON_BANNER, 
  },
  [CategoryId.ASAMUTHA]: {
    id: CategoryId.ASAMUTHA,
    title: 'Asamutha Hasta',
    subtitle: 'Combined Hand Gestures',
    description: 'The 24 Combined Hand Gestures (Samyuta Hastas). These use both hands to portray complex imagery, relationships, and emotional states.',
    heroImage: COMMON_BANNER,
  },
  [CategoryId.NAVARASAS]: {
    id: CategoryId.NAVARASAS,
    title: 'Navarasas',
    subtitle: 'The Nine Emotions',
    description: 'The essence of expression (Abhinaya), capturing the human experience through nine distinct emotional states.',
    heroImage: COMMON_BANNER,
  },
  [CategoryId.HEAD]: {
    id: CategoryId.HEAD,
    title: 'Shiro Bhedas',
    subtitle: 'Head Movements',
    description: 'Movements of the head that dictate the direction and flow of the dance.',
    heroImage: COMMON_BANNER,
  },
  [CategoryId.NECK]: {
    id: CategoryId.NECK,
    title: 'Greeva Bhedas',
    subtitle: 'Neck Movements',
    description: 'Subtle movements of the neck that add grace and fluidity.',
    heroImage: COMMON_BANNER,
  },
  [CategoryId.EYE]: {
    id: CategoryId.EYE,
    title: 'Drishti Bhedas',
    subtitle: 'Eye Movements',
    description: 'Where the hand goes, the eyes follow. Eye movements define the focus.',
    heroImage: COMMON_BANNER,
  },
  [CategoryId.EYEBROW]: {
    id: CategoryId.EYEBROW,
    title: 'Bhru Bhedas',
    subtitle: 'Eyebrow Movements',
    description: 'Intricate movements of the eyebrows to enhance facial expression.',
    heroImage: COMMON_BANNER,
  },
};

// Mock Database Content
export const SAMPLE_ITEMS: DanceItem[] = [
  
  // =========================================================================
  // SAMUTHA (Single Hand) ITEMS - TOTAL 28
  // Images expected in: /public/images/samutha/
  // =========================================================================
  
  {
    id: 'pataka',
    categoryId: CategoryId.SAMUTHA,
    name: 'Pataka',
    sanskritName: 'पताका',
    imageUrl: '/images/samutha/pataka.png',
    description: 'Flag. All fingers extended and joined together. Used to denote clouds, forest, river, open doors, etc.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['tripataka', 'ardhapataka'],
  },
  {
    id: 'tripataka',
    categoryId: CategoryId.SAMUTHA,
    name: 'Tripataka',
    sanskritName: 'त्रिपताका',
    imageUrl: '/images/samutha/tripataka.png',
    description: 'Three parts of the flag. Ring finger bent. Denotes crown, tree, vajra weapon, etc.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'ardhapataka',
    categoryId: CategoryId.SAMUTHA,
    name: 'Ardhapataka',
    sanskritName: 'अर्धपताका',
    imageUrl: '/images/samutha/ardhapataka.png',
    description: 'Half flag. Little finger also bent. Denotes leaves, board, knife, etc.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka', 'tripataka'],
  },
  {
    id: 'kartarimukha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Kartarimukha',
    sanskritName: 'कर्तरीमुख',
    imageUrl: '/images/samutha/kartarimukha.png',
    description: 'Scissors face. Index and middle fingers separated. Denotes separation, corner of eye, death, lightning.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['arala'],
  },
  {
    id: 'mayura',
    categoryId: CategoryId.SAMUTHA,
    name: 'Mayura',
    sanskritName: 'मयूर',
    imageUrl: '/images/samutha/mayura.png',
    description: 'Peacock. Ring finger joins thumb, others extended. Denotes peacock, creeper, bird, decorative mark.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'ardhachandra',
    categoryId: CategoryId.SAMUTHA,
    name: 'Ardhachandra',
    sanskritName: 'अर्धचन्द्र',
    imageUrl: '/images/samutha/ardhachandra.png',
    description: 'Half moon. Thumb stretched out from Pataka. Denotes half moon, spear, throat, platter.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'arala',
    categoryId: CategoryId.SAMUTHA,
    name: 'Arala',
    sanskritName: 'अराल',
    imageUrl: '/images/samutha/arala.png',
    description: 'Bent. Index finger bent. Denotes drinking poison, nectar, violent wind.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shukatunda'],
  },
  {
    id: 'shukatunda',
    categoryId: CategoryId.SAMUTHA,
    name: 'Shukatunda',
    sanskritName: 'शुकतुण्ड',
    imageUrl: '/images/samutha/shukatunda.png',
    description: 'Parrot beak. Ring finger also bent from Arala. Denotes shooting an arrow, throwing a spear, violent mood.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['arala'],
  },
  {
    id: 'mushti',
    categoryId: CategoryId.SAMUTHA,
    name: 'Mushti',
    sanskritName: 'मुष्टि',
    imageUrl: '/images/samutha/mushti.png',
    description: 'Fist. All fingers closed into palm, thumb over them. Denotes steadfastness, grasping hair, holding things, fighting.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shikhara'],
  },
  {
    id: 'shikhara',
    categoryId: CategoryId.SAMUTHA,
    name: 'Shikhara',
    sanskritName: 'शिखर',
    imageUrl: '/images/samutha/shikhara.png',
    description: 'Peak. Thumb raised from Mushti. Denotes bow, pillar, silence, husband, tooth, entering.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['mushti', 'kapittha'],
  },
  {
    id: 'kapittha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Kapittha',
    sanskritName: 'कपित्थ',
    imageUrl: '/images/samutha/kapittha.png',
    description: 'Wood apple. Index finger bent over thumb from Shikhara. Denotes goddess Lakshmi, holding cymbals, milking cows.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shikhara', 'katakamukha'],
  },
  {
    id: 'katakamukha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Katakamukha',
    sanskritName: 'कटकमुख',
    imageUrl: '/images/samutha/katakamukha.png',
    description: 'Opening in a bracelet. Index and middle fingers join thumb. Denotes picking flowers, holding a necklace, speaking, glancing.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['kapittha'],
  },
  {
    id: 'suchi',
    categoryId: CategoryId.SAMUTHA,
    name: 'Suchi',
    sanskritName: 'सूचि',
    imageUrl: '/images/samutha/suchi.png',
    description: 'Needle. Index finger extended. Denotes one, parabrahma, one hundred, sun, city, world.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['chandrakala'],
  },
  {
    id: 'chandrakala',
    categoryId: CategoryId.SAMUTHA,
    name: 'Chandrakala',
    sanskritName: 'चन्द्रकला',
    imageUrl: '/images/samutha/chandrakala.png',
    description: 'Digit of the moon. Thumb released from Suchi. Denotes moon, face, extent between thumb and index finger.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['suchi'],
  },
  {
    id: 'padmakosha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Padmakosha',
    sanskritName: 'पद्मकोश',
    imageUrl: '/images/samutha/padmakosha.png',
    description: 'Lotus bud. Fingers separated and slightly bent, palm hollowed. Denotes fruit, bud, ball, cooking pot, egg.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['alapadma'],
  },
  {
    id: 'sarpashirsha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Sarpashirsha',
    sanskritName: 'सर्पशीर्ष',
    imageUrl: '/images/samutha/sarpashirsha.png',
    description: 'Snake hood. Tips of fingers bent from Pataka. Denotes snake, sprinkling water, offering.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'mrigashirsha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Mrigashirsha',
    sanskritName: 'मृगशीर्ष',
    imageUrl: '/images/samutha/mrigashirsha.png',
    description: 'Deer head. Little finger and thumb extended. Denotes women, cheek, wheel, fear, quarrel.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['simhamukha'],
  },
  {
    id: 'simhamukha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Simhamukha',
    sanskritName: 'सिंहमुख',
    imageUrl: '/images/samutha/simhamukha.png',
    description: 'Lion face. Tips of middle and ring fingers apply to thumb. Denotes lion, hare, elephant, coral.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['mrigashirsha'],
  },
  {
    id: 'kangula',
    categoryId: CategoryId.SAMUTHA,
    name: 'Kangula',
    sanskritName: 'कांगुल',
    imageUrl: '/images/samutha/kangula.png',
    description: 'Tail. Ring finger bent. Denotes lakuch fruit, bells, betel nut.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['padmakosha'],
  },
  {
    id: 'alapadma',
    categoryId: CategoryId.SAMUTHA,
    name: 'Alapadma',
    sanskritName: 'अलपद्म',
    imageUrl: '/images/samutha/alapadma.png',
    description: 'Full blown lotus. Fingers separated and turned. Denotes full blown lotus, circular movement, breast, separation.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['padmakosha'],
  },
  {
    id: 'chatura',
    categoryId: CategoryId.SAMUTHA,
    name: 'Chatura',
    sanskritName: 'चतुर',
    imageUrl: '/images/samutha/chatura.png',
    description: 'Smart/Square. Thumb placed at the base of third finger. Denotes musk, little, gold, copper, wet.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'bhramara',
    categoryId: CategoryId.SAMUTHA,
    name: 'Bhramara',
    sanskritName: 'भ्रमर',
    imageUrl: '/images/samutha/bhramara.png',
    description: 'Bee. Thumb and middle finger joined, index bent, others extended. Denotes bee, parrot, wing.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['hamsasya'],
  },
  {
    id: 'hamsasya',
    categoryId: CategoryId.SAMUTHA,
    name: 'Hamsasya',
    sanskritName: 'हंसास्य',
    imageUrl: '/images/samutha/hamsasya.png',
    description: 'Swan beak. Thumb and index finger joined. Denotes tying thread, initiation, certainty, painting.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['bhramara'],
  },
  {
    id: 'hamsapaksha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Hamsapaksha',
    sanskritName: 'हंसपक्ष',
    imageUrl: '/images/samutha/hamsapaksha.png',
    description: 'Swan wing. Little finger extended, others like Sarpa-shirsha. Denotes number six, construction of bridge, nail marks.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sarpashirsha'],
  },
  {
    id: 'samdamsha',
    categoryId: CategoryId.SAMUTHA,
    name: 'Samdamsha',
    sanskritName: 'संदंश',
    imageUrl: '/images/samutha/samdamsha.png',
    description: 'Pincers. Fingers of Padmakosha are brought together and separated repeatedly. Denotes generosity, sacrificial offering, tumor.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['padmakosha', 'mukula'],
  },
  {
    id: 'mukula',
    categoryId: CategoryId.SAMUTHA,
    name: 'Mukula',
    sanskritName: 'मुकुल',
    imageUrl: '/images/samutha/mukula.png',
    description: 'Bud. Five fingers meet. Denotes water lily, eating, God of Love (Manmatha), holding a seal.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['padmakosha'],
  },
  {
    id: 'tamrachuda',
    categoryId: CategoryId.SAMUTHA,
    name: 'Tamrachuda',
    sanskritName: 'ताम्रचूड',
    imageUrl: '/images/samutha/tamrachuda.png',
    description: 'Cock. Index finger hooked from Mukula. Denotes cock, crane, crow, camel, calf, pen.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['mukula'],
  },
  {
    id: 'trishula',
    categoryId: CategoryId.SAMUTHA,
    name: 'Trishula',
    sanskritName: 'त्रिशूल',
    imageUrl: '/images/samutha/trishula.png',
    description: 'Trident. Thumb and little finger joined. Denotes wood apple leaf, three together.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },


  // =========================================================================
  // ASAMUTHA (Combined Hand) ITEMS - TOTAL 24
  // Images expected in: /public/images/asamutha/
  // =========================================================================

  {
    id: 'anjali',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Anjali',
    sanskritName: 'अंजलि',
    imageUrl: '/images/asamutha/anjali.png', 
    description: 'Salutation. Joining two Pataka hands together. Used for saluting Deities, Gurus, and Brahmanas.',
    youtubeId: 'dQw4w9WgXcQ', // Placeholder ID
    relatedIds: ['pushpaputa'],
  },
  {
    id: 'kapota',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Kapota',
    sanskritName: 'कपोत',
    imageUrl: '/images/asamutha/kapota.png', 
    description: 'Dove. Hands joined at the side, base, and top. Used for salutation, taking oath, or accepting things with humility.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['anjali'],
  },
  {
    id: 'karkata',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Karkata',
    sanskritName: 'कर्कट',
    imageUrl: '/images/asamutha/karkata.png', 
    description: 'Crab. Fingers of hands interlocked. Used to denote multitude, thick bending of a branch, blowing the conch, stretching limbs.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['khatva'],
  },
  {
    id: 'swastika',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Swastika',
    sanskritName: 'स्वस्तिक',
    imageUrl: '/images/asamutha/swastika.png', 
    description: 'Crossed. Two Pataka hands crossed at wrists. Used to denote a crocodile, timid speech, or dispute.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'dola',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Dola',
    sanskritName: 'डोला',
    imageUrl: '/images/asamutha/dola.png', 
    description: 'Swing. Pataka hands placed on thighs. Used to denote the beginning of Natya, pose of ease.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'pushpaputa',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Pushpaputa',
    sanskritName: 'पुष्पपुट',
    imageUrl: '/images/asamutha/pushpaputa.png', 
    description: 'Flower basket. Sarpa-shirsha hands pressed together. Used to denote offering lights (Aarati), drinking water, offering flowers.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sarpashirsha'],
  },
  {
    id: 'utsanga',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Utsanga',
    sanskritName: 'उत्संग',
    imageUrl: '/images/asamutha/utsanga.png', 
    description: 'Embrace. Mrigashirsha hands placed on opposite armpits/shoulders. Used to denote an embrace, modesty, or teaching children.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['mrigashirsha'],
  },
  {
    id: 'shivalinga',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Shivalinga',
    sanskritName: 'शिवलिंग',
    imageUrl: '/images/asamutha/shivalinga.png', 
    description: 'Phallus of Shiva. Ardhachandra with left hand, Shikhara with right. Denotes the Shivalinga icon.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shikhara', 'ardhachandra'],
  },
  {
    id: 'katakavardhana',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Katakavardhana',
    sanskritName: 'कटकवर्धन',
    imageUrl: '/images/asamutha/katakavardhana.png', 
    description: 'Link of chains. Katakamukha hands crossed at wrists. Used to denote coronation, worship, or marriage.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['katakamukha'],
  },
  {
    id: 'kartariswastika',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Kartariswastika',
    sanskritName: 'कर्तरीस्वस्तिक',
    imageUrl: '/images/asamutha/kartariswastika.png', 
    description: 'Crossed scissors. Kartarimukha hands crossed. Denotes branches, trees, or peaks of mountains.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['kartarimukha'],
  },
  {
    id: 'shakata',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Shakata',
    sanskritName: 'शकट',
    imageUrl: '/images/asamutha/shakata.png', 
    description: 'Cart. Bhramara hands with thumb and middle finger extended. Used to denote the gesture of demons (Rakshasa).',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['bhramara'],
  },
  {
    id: 'shankha',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Shankha',
    sanskritName: 'शङ्ख',
    imageUrl: '/images/asamutha/shankha.png', 
    description: 'Conch. Thumbs of Shikhara joined to other fingers. Denotes the conch shell.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shikhara'],
  },
  {
    id: 'chakra',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Chakra',
    sanskritName: 'चक्र',
    imageUrl: '/images/asamutha/chakra.png', 
    description: 'Wheel. Ardhachandra hands crossed. Denotes a wheel (Discus of Vishnu).',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['ardhachandra'],
  },
  {
    id: 'samputa',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Samputa',
    sanskritName: 'सम्पुट',
    imageUrl: '/images/asamutha/samputa.png', 
    description: 'Casket. Fingers of Chakra are bent. Denotes concealing things, or a container.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['chakra'],
  },
  {
    id: 'pasha',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Pasha',
    sanskritName: 'पाश',
    imageUrl: '/images/asamutha/pasha.png', 
    description: 'Noose. Forefingers of Suchi are interlocked. Denotes internal quarrel, string, or chain.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['suchi'],
  },
  {
    id: 'kilaka',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Kilaka',
    sanskritName: 'कीलक',
    imageUrl: '/images/asamutha/kilaka.png', 
    description: 'Bond. Little fingers of Mrigashirsha are interlocked. Denotes affection or conversation of lovers.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['mrigashirsha'],
  },
  {
    id: 'matsya',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Matsya',
    sanskritName: 'मत्स्य',
    imageUrl: '/images/asamutha/matsya.png', 
    description: 'Fish. Pataka hands placed on top of each other, thumbs extended. Denotes a fish or the Matsya avatar of Vishnu.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pataka'],
  },
  {
    id: 'kurma',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Kurma',
    sanskritName: 'कूर्म',
    imageUrl: '/images/asamutha/kurma.png', 
    description: 'Tortoise. Ends of fingers bent of Chakra hand, thumbs not joined. Denotes a tortoise or Kurma avatar.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['chakra'],
  },
  {
    id: 'varaha',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Varaha',
    sanskritName: 'वराह',
    imageUrl: '/images/asamutha/varaha.png', 
    description: 'Boar. Mrigashirsha hands placed one over other, thumbs joined. Denotes a boar or Varaha avatar.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['mrigashirsha'],
  },
  {
    id: 'garuda',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Garuda',
    sanskritName: 'गरुड',
    imageUrl: '/images/asamutha/garuda.png', 
    description: 'Eagle. Ardhachandra hands crossed at thumbs. Denotes Garuda (vehicle of Vishnu) or birds flying.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['ardhachandra'],
  },
  {
    id: 'nagabandha',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Nagabandha',
    sanskritName: 'नागबन्ध',
    imageUrl: '/images/asamutha/nagabandha.png', 
    description: 'Serpent tie. Sarpashirsha hands crossed. Denotes pairs of snakes or creepers.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sarpashirsha'],
  },
  {
    id: 'khatva',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Khatva',
    sanskritName: 'खट्वा',
    imageUrl: '/images/asamutha/khatva.png', 
    description: 'Bed. Chatura hands placed on top of one another. Denotes a bed or palanquin.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['chatura'],
  },
  {
    id: 'bherunda',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Bherunda',
    sanskritName: 'भेरुण्ड',
    imageUrl: '/images/asamutha/bherunda.png', 
    description: 'Pair of birds. Kapittha hands joined at wrists. Denotes a pair of Bherunda birds.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['kapittha'],
  },
  {
    id: 'avahittha',
    categoryId: CategoryId.ASAMUTHA,
    name: 'Avahittha',
    sanskritName: 'अवहित्थ',
    imageUrl: '/images/asamutha/avahittha.png', 
    description: 'Dissimulation. Alapadma hands held near the chest. Denotes erotic interest, holding play balls, or bosom.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['alapadma'],
  },

  // =========================================================================
  // NAVARASAS (Nine Emotions) ITEMS - TOTAL 9
  // Images expected in: /public/images/navarasas/
  // =========================================================================
  {
    id: 'shringara',
    categoryId: CategoryId.NAVARASAS,
    name: 'Shringara',
    sanskritName: 'शृङ्गार',
    imageUrl: '/images/navarasas/shringara.png',
    description: 'Love and Beauty. The ultimate sentiment, encompassing devotion, romantic love, and parental love.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['hasya', 'karuna'],
  },
  {
    id: 'hasya',
    categoryId: CategoryId.NAVARASAS,
    name: 'Hasya',
    sanskritName: 'हास्य',
    imageUrl: '/images/navarasas/hasya.png',
    description: 'Laughter and Mirth. Joyful humor, satire, or simple happiness.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shringara', 'adbhuta'],
  },
  {
    id: 'karuna',
    categoryId: CategoryId.NAVARASAS,
    name: 'Karuna',
    sanskritName: 'करुणा',
    imageUrl: '/images/navarasas/karuna.png',
    description: 'Compassion and Sorrow. A state of grief or pity, often invoking empathy in the viewer.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['shringara', 'shanta'],
  },
  {
    id: 'raudra',
    categoryId: CategoryId.NAVARASAS,
    name: 'Raudra',
    sanskritName: 'रौद्र',
    imageUrl: '/images/navarasas/raudra.png',
    description: 'Anger and Fury. Used to depict destruction, war, or offense.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['veera', 'bhayanaka'],
  },
  {
    id: 'veera',
    categoryId: CategoryId.NAVARASAS,
    name: 'Veera',
    sanskritName: 'वीर',
    imageUrl: '/images/navarasas/veera.png',
    description: 'Heroism and Courage. Displays bravery, confidence, and determination.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['raudra', 'adbhuta'],
  },
  {
    id: 'bhayanaka',
    categoryId: CategoryId.NAVARASAS,
    name: 'Bhayanaka',
    sanskritName: 'भयानक',
    imageUrl: '/images/navarasas/bhayanaka.png',
    description: 'Fear and Terror. Expresses anxiety, dread, or shock.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['raudra', 'bibhatsa'],
  },
  {
    id: 'bibhatsa',
    categoryId: CategoryId.NAVARASAS,
    name: 'Bibhatsa',
    sanskritName: 'बीभत्स',
    imageUrl: '/images/navarasas/bibhatsa.png',
    description: 'Disgust and Aversion. Used for unpleasant, loathsome, or repulsive subjects.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['bhayanaka', 'raudra'],
  },
  {
    id: 'adbhuta',
    categoryId: CategoryId.NAVARASAS,
    name: 'Adbhuta',
    sanskritName: 'अद्भुत',
    imageUrl: '/images/navarasas/adbhuta.png',
    description: 'Wonder and Astonishment. Expresses surprise, awe, or amazement.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['hasya', 'veera'],
  },
  {
    id: 'shanta',
    categoryId: CategoryId.NAVARASAS,
    name: 'Shanta',
    sanskritName: 'शान्त',
    imageUrl: '/images/navarasas/shanta.png',
    description: 'Peace and Tranquility. A state of calm, liberation, and spiritual peace.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['karuna', 'shringara'],
  },
  
  // =========================================================================
  // SHIRO BHEDAS (Head Movements) ITEMS - TOTAL 9
  // Images expected in: /public/images/head/
  // =========================================================================
  {
    id: 'sama',
    categoryId: CategoryId.HEAD,
    name: 'Sama',
    sanskritName: 'सम',
    imageUrl: '/images/head/sama.png',
    description: 'The head is kept straight without any movement. Denotes beginning of dance, prayer, or pride.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['udvahita'],
  },
  {
    id: 'udvahita',
    categoryId: CategoryId.HEAD,
    name: 'Udvahita',
    sanskritName: 'उद्वहित',
    imageUrl: '/images/head/udvahita.png',
    description: 'Head raised upwards. Denotes looking at the flag, moon, sky, or mountain.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sama', 'adhomukha'],
  },
  {
    id: 'adhomukha',
    categoryId: CategoryId.HEAD,
    name: 'Adhomukha',
    sanskritName: 'अधोमुख',
    imageUrl: '/images/head/adhomukha.png',
    description: 'Head bent downwards. Denotes shyness, sorrow, bowing, or looking at something on the ground.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['udvahita'],
  },
  {
    id: 'alolita',
    categoryId: CategoryId.HEAD,
    name: 'Alolitam',
    sanskritName: 'आलोलित',
    imageUrl: '/images/head/alolita.png',
    description: 'Rolling the head in a circle. Denotes sleepiness, obsession, intoxication, or uncontrollable laughter.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sama'],
  },
  {
    id: 'dhuta',
    categoryId: CategoryId.HEAD,
    name: 'Dhutam',
    sanskritName: 'धुत',
    imageUrl: '/images/head/dhuta.png',
    description: 'Shaking head from side to side (No). Denotes denial, looking repeatedly at sides, or astonishment.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['kampita'],
  },
  {
    id: 'kampita',
    categoryId: CategoryId.HEAD,
    name: 'Kampitam',
    sanskritName: 'कम्पित',
    imageUrl: '/images/head/kampita.png',
    description: 'Shaking head up and down (Nod). Denotes calling someone, inquiry, understanding, or threatening.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['dhuta'],
  },
  {
    id: 'paravritta',
    categoryId: CategoryId.HEAD,
    name: 'Paravrittam',
    sanskritName: 'परावृत्त',
    imageUrl: '/images/head/paravritta.png',
    description: 'Head turned aside completely. Denotes looking back, indifference, or turning away in anger.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sama'],
  },
  {
    id: 'utkshipta',
    categoryId: CategoryId.HEAD,
    name: 'Utkshiptam',
    sanskritName: 'उत्क्षिप्त',
    imageUrl: '/images/head/utkshipta.png',
    description: 'Head turned aside and raised. Denotes looking at lofty objects or divine beings.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['udvahita'],
  },
  {
    id: 'parivahitta',
    categoryId: CategoryId.HEAD,
    name: 'Parivahittam',
    sanskritName: 'परिवहित्त',
    imageUrl: '/images/head/parivahitta.png',
    description: 'Head wagging from side to side rapidly. Denotes shivering, gratification, or reflection.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['dhuta'],
  },

  // =========================================================================
  // GREEVA BHEDAS (Neck Movements) ITEMS - TOTAL 4
  // Images expected in: /public/images/neck/
  // =========================================================================
  {
    id: 'sundari',
    categoryId: CategoryId.NECK,
    name: 'Sundari',
    sanskritName: 'सुन्दरी',
    imageUrl: '/images/neck/sundari.png',
    description: 'Neck moves horizontally to the sides. Denotes friendship, verification, or pleasure.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['tiraschina'],
  },
  {
    id: 'tiraschina',
    categoryId: CategoryId.NECK,
    name: 'Tiraschina',
    sanskritName: 'तिरश्चीन',
    imageUrl: '/images/neck/tiraschina.png',
    description: 'Upward side movement of neck (gliding like a snake). Denotes brandishing a sword or gliding of a snake.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sundari'],
  },
  {
    id: 'parivartita',
    categoryId: CategoryId.NECK,
    name: 'Parivartita',
    sanskritName: 'परिवर्तित',
    imageUrl: '/images/neck/parivartita.png',
    description: 'Neck moves in a semicircle. Denotes erotic dancing or kissing the cheeks.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['prakampita'],
  },
  {
    id: 'prakampita',
    categoryId: CategoryId.NECK,
    name: 'Prakampita',
    sanskritName: 'प्रकम्पित',
    imageUrl: '/images/neck/prakampita.png',
    description: 'Neck moves forward and backward like a pigeon. Denotes saying "You and I", swinging, or counting.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sundari'],
  },

  // =========================================================================
  // DRISHTI BHEDAS (Eye Movements) ITEMS - TOTAL 8
  // Images expected in: /public/images/eye/
  // =========================================================================
  {
    id: 'sama_eye',
    categoryId: CategoryId.EYE,
    name: 'Sama',
    sanskritName: 'सम',
    imageUrl: '/images/eye/sama.png',
    description: 'Gazing straight without blinking. Denotes beginning of dance, scales, or surprise.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['alokita'],
  },
  {
    id: 'alokita',
    categoryId: CategoryId.EYE,
    name: 'Alokita',
    sanskritName: 'आलोकित',
    imageUrl: '/images/eye/alokita.png',
    description: 'Rolling eyes in a circle. Denotes pottery wheel or all-round view.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sama_eye'],
  },
  {
    id: 'sachi',
    categoryId: CategoryId.EYE,
    name: 'Sachi',
    sanskritName: 'साची',
    imageUrl: '/images/eye/sachi.png',
    description: 'Looking out of the corner of the eye. Denotes hint, desire, or aiming an arrow.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['pralokita'],
  },
  {
    id: 'pralokita',
    categoryId: CategoryId.EYE,
    name: 'Pralokita',
    sanskritName: 'प्रलोकित',
    imageUrl: '/images/eye/pralokita.png',
    description: 'Looking to the sides. Denotes pointing to things on both sides or moving objects.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sachi'],
  },
  {
    id: 'nimilita',
    categoryId: CategoryId.EYE,
    name: 'Nimilita',
    sanskritName: 'निमीलित',
    imageUrl: '/images/eye/nimilita.png',
    description: 'Half-closed eyes. Denotes snake, meditation, prayer, or sickness.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['sama_eye'],
  },
  {
    id: 'ullokita',
    categoryId: CategoryId.EYE,
    name: 'Ullokita',
    sanskritName: 'उल्लोकित',
    imageUrl: '/images/eye/ullokita.png',
    description: 'Looking up. Denotes top of flag, tower, temple, or celestial bodies.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['avalokita'],
  },
  {
    id: 'anuvritta',
    categoryId: CategoryId.EYE,
    name: 'Anuvritta',
    sanskritName: 'अनुवृत्त',
    imageUrl: '/images/eye/anuvritta.png',
    description: 'Glancing up and down quickly. Denotes anger or greeting.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['ullokita'],
  },
  {
    id: 'avalokita',
    categoryId: CategoryId.EYE,
    name: 'Avalokita',
    sanskritName: 'अवलोकित',
    imageUrl: '/images/eye/avalokita.png',
    description: 'Looking down. Denotes looking at shadow, reflection, fatigue, or study.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['ullokita'],
  },

  // =========================================================================
  // BHRU BHEDAS (Eyebrow Movements) ITEMS - TOTAL 6
  // Images expected in: /public/images/eyebrow/
  // =========================================================================
  {
    id: 'sahaja',
    categoryId: CategoryId.EYEBROW,
    name: 'Sahaja',
    sanskritName: 'सहज',
    imageUrl: '/images/eyebrow/sahaja.png',
    description: 'Natural position of eyebrows. Denotes natural state.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['patita'],
  },
  {
    id: 'patita',
    categoryId: CategoryId.EYEBROW,
    name: 'Patita',
    sanskritName: 'पतित',
    imageUrl: '/images/eyebrow/patita.png',
    description: 'Eyebrows lowered. Denotes disgust, astonishment, or jealousy.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['utkshipta'],
  },
  {
    id: 'utkshipta_brow',
    categoryId: CategoryId.EYEBROW,
    name: 'Utkshipta',
    sanskritName: 'उत्क्षिप्त',
    imageUrl: '/images/eyebrow/utkshipta.png',
    description: 'Eyebrows raised. Denotes woman, anger, surprise, or looking.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['patita'],
  },
  {
    id: 'chatura_brow',
    categoryId: CategoryId.EYEBROW,
    name: 'Chatura',
    sanskritName: 'चतुर',
    imageUrl: '/images/eyebrow/chatura.png',
    description: 'Eyebrows expanded/stretched. Denotes love, smile, or touching one another.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['kunchita'],
  },
  {
    id: 'rechita',
    categoryId: CategoryId.EYEBROW,
    name: 'Rechita',
    sanskritName: 'रेचित',
    imageUrl: '/images/eyebrow/rechita.png',
    description: 'Raising one eyebrow. Denotes sporting, questioning, or charm.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['utkshipta_brow'],
  },
  {
    id: 'kunchita',
    categoryId: CategoryId.EYEBROW,
    name: 'Kunchita',
    sanskritName: 'कुञ्चित',
    imageUrl: '/images/eyebrow/kunchita.png',
    description: 'Eyebrows curved downwards. Denotes sorrow, crying, or fear.',
    youtubeId: 'dQw4w9WgXcQ',
    relatedIds: ['patita'],
  },
];

// Helper to get items by category
export const getItemsByCategory = (categoryId: CategoryId): DanceItem[] => {
  return SAMPLE_ITEMS.filter(item => item.categoryId === categoryId);
};

// Helper to get specific item
export const getItemById = (id: string): DanceItem | undefined => {
  return SAMPLE_ITEMS.find(item => item.id === id);
};

// Helper to get related items
export const getRelatedItems = (ids: string[]): DanceItem[] => {
  return SAMPLE_ITEMS.filter(item => ids.includes(item.id));
};